model_name: cnn

in_channels: ???           
out_channels: 100
kernel_sizes: [3, 5, 7]    
activation: 'gelu'         # [relu, lrelu, prelu, selu, celu, gelu, sigmoid, tanh]
pooling_strategy: 'max'    # [max, avg, cls]
keep_length: True
dropout: 0.3

# pcnn
use_pcnn: False
intermediate: 80
