model_name: lm


lm_file: 'F:///deepke-master/pretrained/data'

num_hidden_layers: 1

type_rnn: 'LSTM'    # [RNN, GRU, LSTM]
input_size: 768     # 
hidden_size: 100    # 
num_layers: 1
dropout: 0.3
bidirectional: True
last_layer_hn: True