seed: 1

use_gpu: True
gpu_id: 0

# 主动学习策略
select_method: 'uncertainty' 
concrete: 'entropy_sampling' 

epoch: 10
batch_size: 128
learning_rate: 3e-4
lr_factor: 0.7 
lr_patience: 3 
weight_decay: 1e-3 

early_stopping_patience: 6

train_log: True
log_interval: 10
show_plot: True
only_comparison_plot: False
plot_utils: tensorboard  # [matplot, tensorboard]

predict_plot: True